"""Model Failure Atlas: where does a classifier get things wrong?

    streamlit run app.py

The app analyses predictions that already exist in a CSV. It never trains
or runs a model. Every number comes from analysis.py; this file only lays
out the page and keeps the interaction state consistent.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

import altair as alt
import numpy as np
import pandas as pd
import streamlit as st

import analysis as A

SAMPLE_PATH = Path(__file__).parent / "sample_predictions.csv"

# Error rate is a magnitude, so it gets one hue from light to dark: steps
# 100-700 of a blue ramp, spread evenly over a fixed 0-100% domain. Dark
# themes flip the anchor so a higher rate is always the more prominent cell.
BLUE_RAMP = [
    "#cde2fb", "#b7d3f6", "#9ec5f4", "#86b6ef", "#6da7ec", "#5598e7", "#3987e5",
    "#2a78d6", "#256abf", "#1c5cab", "#184f95", "#104281", "#0d366b",
]
INK, WHITE, MUTED = "#0b0b0b", "#ffffff", "#898781"
EMPTY_FILL = "rgba(137, 135, 129, 0.16)"  # neutral wash that works on light and dark
DIAGONAL_FILL = "background-color: rgba(137, 135, 129, 0.18); font-weight: 600"
TEXT_FLIP = 0.58  # from ramp step 450 on, white text contrasts better than ink
MAX_MATRIX_CLASSES = 30

CSV_HELP = """
One row per evaluated example, with a header row. For example:

```text
image_id,actual,predicted,confidence,brightness,blur_px
img_00001,stop,no_entry,0.43,0.21,6.4
img_00002,yield,yield,0.91,0.77,1.2
```

* **Actual and predicted labels**: any column names; you choose them after uploading.
* **At least two numeric feature columns** to use as the map's axes.
* Optional: an ID column and a confidence column (the probability the model
  gave to the class it predicted, between 0 and 1).
"""


@dataclass(frozen=True)
class Settings:
    n_bins: int
    small_n: int


@dataclass(frozen=True)
class Roles:
    actual: str
    predicted: str
    ids: tuple[str, ...]
    confidence: str | None  # the column picked as confidence, confirmed or not
    confidence_ok: bool  # confirmed as predicted-class probability and within 0-1

    @property
    def reserved(self) -> dict[str, str]:
        """Columns that already have a role, so they can't be map axes."""
        reserved = {self.actual: "actual label", self.predicted: "predicted label"}
        reserved.update({column: "identifier" for column in self.ids})
        if self.confidence:
            reserved[self.confidence] = "confidence"
        return reserved


def md(text: object) -> str:
    """Escape text from the CSV so Markdown never reformats it."""
    return re.sub(r"([\\`*_{}\[\]()#+\-.!|$<>~])", r"\\\1", str(text))


def plural(n: int, word: str) -> str:
    return f"{n:,} {word if n == 1 else word + 's'}"


def percent_table(frame: pd.DataFrame, *columns: str) -> pd.DataFrame:
    """Rates (0-1) as percentages, for tables that show them to one decimal place."""
    return frame.assign(**{column: frame[column] * 100 for column in columns})


def percent_column(label: str | None = None):
    return st.column_config.NumberColumn(label, format="%.1f%%")


def theme_is_dark() -> bool:
    try:
        return st.context.theme.type == "dark"
    except Exception:  # no browser context, e.g. in tests
        return False


# The cache is shared by every visitor to a deployed app, so keep it small.
@st.cache_data(show_spinner=False, max_entries=4, ttl="1h")
def load(data: bytes) -> A.LoadedCSV:
    return A.load_csv(data)


# ---------------------------------------------------------------------------
# Sidebar


def choose_dataset() -> tuple[bytes, str, str] | None:
    """Returns (bytes, display name, dataset key); None while waiting for an upload."""
    st.subheader("Data")
    source = st.radio(
        "Data source",
        ["Sample dataset", "Upload a CSV"],
        key="source",
        label_visibility="collapsed",
    )
    if source == "Sample dataset":
        st.caption(
            "Synthetic results from a traffic-sign classifier on 1,200 images, "
            "generated by `scripts/make_sample_data.py`."
        )
        return SAMPLE_PATH.read_bytes(), SAMPLE_PATH.name, "sample"
    upload = st.file_uploader(
        "CSV of predictions",
        type=["csv"],
        key="upload",
        help="One row per evaluated example, with a header row.",
    )
    if upload is None:
        return None
    # A fresh upload gets a fresh key, even if it is the same file, so no
    # choices from the previous dataset carry over.
    return upload.getvalue(), upload.name, f"upload:{upload.file_id}"


def map_settings() -> Settings:
    st.subheader("Map settings")
    n_bins = st.select_slider(
        "Ranges per axis",
        options=list(range(2, 9)),
        value=A.DEFAULT_BINS,
        key="n_bins",
        help="Each feature is split into this many equal-width ranges. "
        "Changing it clears the selected cell.",
    )
    small_n = st.number_input(
        "Small-sample threshold",
        min_value=2,
        max_value=100_000,
        value=A.DEFAULT_SMALL_SAMPLE,
        step=1,
        key="small_n",
        help="Cells with fewer examples than this are marked as small samples, "
        "because their error rates are unreliable.",
    )
    return Settings(int(n_bins), int(small_n))


# ---------------------------------------------------------------------------
# 1 · Data


def pick_column(label: str, options: list[str], guess: str | None, key: str, **kwargs) -> str | None:
    index = options.index(guess) if guess in options else None
    return st.selectbox(label, options, index=index, key=key, placeholder="Choose a column", **kwargs)


def data_section(raw: pd.DataFrame, loaded: A.LoadedCSV, name: str, dk: str) -> tuple[Roles, A.Evaluation] | None:
    st.header("1 · Data", divider="gray")
    synthetic = " · synthetic demo data" if dk == "sample" else ""
    st.caption(f"**{md(name)}** · {len(raw):,} rows × {raw.shape[1]} columns{synthetic}")
    for note in loaded.notes:
        st.warning(md(note))
    with st.expander("Preview the first rows"):
        st.dataframe(raw.head(20))

    columns = list(raw.columns)
    actual_guess, predicted_guess = A.suggest_label_columns(columns)
    left, right = st.columns(2)
    with left:
        actual_col = pick_column(
            "Actual label column", columns, actual_guess, f"actual::{dk}",
            help="The true class for each example.",
        )
    with right:
        predicted_col = pick_column(
            "Predicted label column", columns, predicted_guess, f"predicted::{dk}",
            help="The class the model predicted for each example.",
        )
    if actual_col is None or predicted_col is None:
        st.info("Choose the actual and predicted label columns to continue.")
        return None
    if actual_col == predicted_col:
        st.error("The actual and predicted labels must come from two different columns.")
        return None

    evaluation = A.evaluate(raw, actual_col, predicted_col)
    report_exclusions(evaluation)
    if evaluation.n_evaluated == 0:
        st.error(
            "No row has both an actual and a predicted label, so there is nothing to "
            "evaluate. Check the column choices above."
        )
        return None

    labels = pd.concat([evaluation.rows["actual"], evaluation.rows["predicted"]])
    variants = A.find_label_variants(labels)
    if variants:
        shown = "; ".join(" / ".join(f"“{md(v)}”" for v in group) for group in variants[:6])
        more = f" (and {len(variants) - 6} more)" if len(variants) > 6 else ""
        st.warning(
            "Some labels differ only in capitalisation, spacing or number format: "
            f"{shown}{more}. They are treated as **different** classes, so a mismatch "
            "between them counts as an error. Fix the file if they mean the same thing."
        )

    with st.expander("Optional columns: identifiers and confidence"):
        roles = optional_roles(raw, evaluation, actual_col, predicted_col, dk)
    return roles, evaluation


def report_exclusions(evaluation: A.Evaluation) -> None:
    if not evaluation.n_excluded:
        st.success(
            f"{evaluation.n_uploaded:,} rows uploaded. Every row has both labels, "
            f"so the analysis uses all {evaluation.n_evaluated:,} rows."
        )
        return
    reasons = [
        (evaluation.n_missing_actual, "no actual label"),
        (evaluation.n_missing_predicted, "no predicted label"),
        (evaluation.n_missing_both, "neither label"),
    ]
    detail = ", ".join(f"{n:,} with {reason}" for n, reason in reasons if n)
    st.warning(
        f"{evaluation.n_uploaded:,} rows uploaded. {plural(evaluation.n_excluded, 'row')} "
        f"excluded because the actual or predicted label was missing ({detail}). "
        f"Analysis uses {evaluation.n_evaluated:,} rows."
    )


def optional_roles(raw: pd.DataFrame, evaluation: A.Evaluation, actual: str, predicted: str, dk: str) -> Roles:
    others = [column for column in raw.columns if column not in (actual, predicted)]
    id_guess = A.suggest_id_columns(raw, exclude=(actual, predicted))
    ids = st.multiselect(
        "Identifier columns",
        others,
        default=[column for column in id_guess if column in others],
        key=f"ids::{dk}",
        help="IDs, codes and row numbers are never offered as map axes, even when "
        "they look numeric. Pre-filled with columns that look like identifiers.",
    )

    conf_options: list[str | None] = [None] + [column for column in others if column not in ids]
    conf_guess = A.suggest_confidence_column(conf_options[1:])
    confidence = st.selectbox(
        "Confidence column",
        conf_options,
        index=conf_options.index(conf_guess),
        format_func=lambda column: "None" if column is None else column,
        key=f"confidence::{dk}",
        help="Optional. Only used once you confirm what it means.",
    )
    confidence_ok = False
    if confidence is not None:
        confirmed = st.checkbox(
            f"“{md(confidence)}” is the probability the model gave to the class it predicted (0 to 1)",
            key=f"confidence_ok::{dk}::{confidence}",
            help="Not a positive-class probability and not a raw score. If unsure, leave "
            "this unticked: accuracy and the failure map don't need confidence.",
        )
        if confirmed:
            check = A.check_confidence(raw, evaluation.rows.index, confidence)
            if check.usable:
                confidence_ok = True
                st.caption(check.message)
            else:
                st.warning(check.message)
        else:
            st.caption("Confidence is shown in the tables only after you confirm its meaning.")
    return Roles(actual, predicted, tuple(ids), confidence, confidence_ok)


# ---------------------------------------------------------------------------
# 2 · Overall performance


def style_confusion(confusion: pd.DataFrame):
    def diagonal(frame: pd.DataFrame) -> pd.DataFrame:
        styles = pd.DataFrame("", index=frame.index, columns=frame.columns)
        for label in frame.index:
            if label in frame.columns:
                styles.loc[label, label] = DIAGONAL_FILL
        return styles

    return confusion.style.apply(diagonal, axis=None)


def overview_section(
    raw: pd.DataFrame, evaluation: A.Evaluation, overview: A.Overview, roles: Roles, numeric: tuple[str, ...]
) -> None:
    st.header("2 · Overall performance", divider="gray")
    tiles = st.columns(5)
    tiles[0].metric("Accuracy", f"{overview.accuracy:.1%}", border=True, help="Correct predictions ÷ evaluated rows.")
    tiles[1].metric(
        "Errors", f"{overview.n_errors:,}", border=True,
        help="Rows whose predicted label differs from the actual label.",
    )
    tiles[2].metric("Correct", f"{overview.n_correct:,}", border=True)
    tiles[3].metric(
        "Evaluated rows", f"{overview.n_evaluated:,}", border=True,
        help="Rows with both an actual and a predicted label: the denominator for accuracy.",
    )
    tiles[4].metric(
        "Excluded rows", f"{evaluation.n_excluded:,}", border=True,
        help="Rows missing a label. They are left out of every number on this page.",
    )
    st.caption(
        f"Accuracy = {overview.n_correct:,} correct ÷ {overview.n_evaluated:,} evaluated rows "
        f"(error rate {overview.error_rate:.1%}). Every row counts equally."
    )

    n_classes = len(overview.confusion)
    if n_classes > MAX_MATRIX_CLASSES and n_classes > 0.2 * overview.n_evaluated:
        st.warning(
            f"There are {n_classes:,} distinct labels. This app is built for classification; "
            "if these are continuous values, check the label columns."
        )

    left, right = st.columns([3, 2], gap="large")
    with left:
        st.subheader("Confusion matrix")
        if n_classes > MAX_MATRIX_CLASSES:
            st.info(f"{n_classes:,} classes are too many to show as a matrix. See the most common mistakes.")
        else:
            st.caption(
                "Rows are the actual class, columns the predicted class. "
                "The shaded diagonal counts correct predictions."
            )
            st.dataframe(style_confusion(overview.confusion))
        if overview.predicted_only:
            st.caption(
                "Predicted but never an actual label here: "
                + ", ".join(f"“{md(c)}”" for c in overview.predicted_only) + "."
            )
        if overview.never_predicted:
            st.caption(
                "Actual classes the model never predicted: "
                + ", ".join(f"“{md(c)}”" for c in overview.never_predicted) + "."
            )
    with right:
        st.subheader("Most common mistakes")
        mistakes = A.top_confusions(overview, limit=6)
        if mistakes.empty:
            st.success("No mistakes: every evaluated prediction is correct.")
        else:
            st.dataframe(
                percent_table(mistakes, "share of errors"),
                hide_index=True,
                column_config={
                    "errors": st.column_config.NumberColumn(format="%d"),
                    "share of errors": percent_column(),
                },
            )

    error_index = evaluation.rows.index[evaluation.rows["is_error"]]
    with st.expander(f"All {plural(len(error_index), 'error')}"):
        show_rows(raw, evaluation, error_index, roles, lead=(), numeric=numeric)


# ---------------------------------------------------------------------------
# 3 · Failure map


def pick_axis(label: str, options: tuple[str, ...], key: str, avoid: str | None) -> str:
    preferred = next((column for column in options if column != avoid), options[0])
    return st.selectbox(label, options, index=options.index(preferred), key=key)


def heatmap(fmap: A.FailureMap, small_n: int, selected: tuple[int | None, int | None], dark: bool) -> alt.LayerChart:
    cells = fmap.cells.copy()
    cells["x_range"] = [fmap.x_bins.labels[i] for i in cells["x_bin"]]
    cells["y_range"] = [fmap.y_bins.labels[i] for i in cells["y_bin"]]
    small = A.small_cells(cells, small_n).to_numpy()
    empty = (cells["total"] == 0).to_numpy()
    rate = cells["error_rate"].to_numpy(dtype=float)

    cells["rate_label"] = [f"{r:.0%}" if not e else "" for r, e in zip(rate, empty)]
    cells["count_label"] = [
        "" if e else f"{errors:,} of {total:,}" + (" · small" if s else "")
        for errors, total, e, s in zip(cells["errors"], cells["total"], empty, small)
    ]
    cells["tip_rate"] = [f"{r:.1%}" if not e else "no examples" for r, e in zip(rate, empty)]
    cells["tip_note"] = np.where(small, f"Small sample (fewer than {small_n})", np.where(empty, "Empty: no rate", ""))

    ramp = BLUE_RAMP[::-1] if dark else BLUE_RAMP
    cells["dark_fill"] = (rate <= 1 - TEXT_FLIP) if dark else (rate >= TEXT_FLIP)
    # A condition, not a colour scale: a scale here would be merged with the
    # error-rate scale across layers, which Vega-Lite can't render.
    text_color = alt.when(alt.datum.dark_fill).then(alt.value(WHITE)).otherwise(alt.value(INK))

    n_x, n_y = len(fmap.x_bins), len(fmap.y_bins)
    big_font = 18 if max(n_x, n_y) <= 4 else 15 if max(n_x, n_y) <= 6 else 12
    small_font = 12 if max(n_x, n_y) <= 5 else 10
    cell_height = 92 if n_y <= 4 else 72 if n_y <= 6 else 56

    x = alt.X(
        "x_range:O",
        sort=list(fmap.x_bins.labels),
        title=fmap.x_col,
        scale=alt.Scale(paddingInner=0.015),
        axis=alt.Axis(labelAngle=0 if n_x <= 5 else -30, domain=False, ticks=False, labelPadding=8),
    )
    y = alt.Y(
        "y_range:O",
        sort=list(reversed(fmap.y_bins.labels)),
        title=fmap.y_col,
        scale=alt.Scale(paddingInner=0.03),
        axis=alt.Axis(domain=False, ticks=False, labelPadding=8),
    )
    base = alt.Chart(cells).encode(x=x, y=y)
    filled = base.transform_filter("datum.total > 0")

    layers = [
        filled.mark_rect(cornerRadius=3).encode(
            color=alt.Color(
                "error_rate:Q",
                title="Error rate",
                scale=alt.Scale(domain=list(np.linspace(0, 1, len(ramp))), range=ramp, clamp=True),
                legend=alt.Legend(format=".0%", values=[0, 0.25, 0.5, 0.75, 1], gradientLength=cell_height * n_y * 0.6),
            )
        ),
        base.transform_filter("datum.total == 0").mark_rect(cornerRadius=3, color=EMPTY_FILL),
        filled.mark_text(fontSize=big_font, fontWeight=600, baseline="bottom", dy=-1).encode(
            text="rate_label:N", color=text_color
        ),
        filled.mark_text(fontSize=small_font, baseline="top", dy=3).encode(
            text="count_label:N", color=text_color
        ),
        base.transform_filter("datum.total == 0").mark_text(fontSize=small_font, color=MUTED).encode(
            text=alt.value("no examples")
        ),
    ]
    sel_x, sel_y = selected
    if sel_x is not None and sel_y is not None:
        layers.append(
            base.transform_filter(f"datum.x_bin == {int(sel_x)} && datum.y_bin == {int(sel_y)}").mark_rect(
                filled=False, stroke=WHITE if dark else INK, strokeWidth=3, cornerRadius=3
            )
        )
    # Invisible top layer: it takes hover and clicks for every cell, empty or not.
    pick = alt.selection_point(name="cell", fields=["x_bin", "y_bin"], on="click", clear=False)
    layers.append(
        base.mark_rect(opacity=0.001, cursor="pointer")
        .encode(
            tooltip=[
                alt.Tooltip("tip_rate:N", title="Error rate"),
                alt.Tooltip("errors:Q", title="Errors", format=","),
                alt.Tooltip("total:Q", title="Examples", format=","),
                alt.Tooltip("x_range:N", title=fmap.x_col),
                alt.Tooltip("y_range:N", title=fmap.y_col),
                alt.Tooltip("tip_note:N", title="Note"),
            ]
        )
        .add_params(pick)
    )
    return (
        alt.layer(*layers)
        .properties(width="container", height=cell_height * n_y)
        .configure_view(stroke=None)
    )


def apply_map_click(chart_key: str) -> None:
    """Copy a click on the map into the two range selectors.

    After a click is applied the chart gets a new key, so its own selection
    state starts empty and the next click always registers as new.
    """
    state = st.session_state.get(chart_key)
    points = (state or {}).get("selection", {}).get("cell") or []
    if points and isinstance(points, list):
        st.session_state["sel_x"] = int(points[0]["x_bin"])
        st.session_state["sel_y"] = int(points[0]["y_bin"])
        st.session_state["map_clicks"] = st.session_state.get("map_clicks", 0) + 1


def failure_map_section(
    raw: pd.DataFrame,
    evaluation: A.Evaluation,
    roles: Roles,
    options: A.FeatureOptions,
    settings: Settings,
    dk: str,
) -> A.FailureMap | None:
    st.header("3 · Failure map", divider="gray")
    not_offered = {c: r for c, r in options.excluded.items() if c not in (roles.actual, roles.predicted)}

    if len(options.usable) < 2:
        found = f"only “{md(options.usable[0])}”" if options.usable else "none"
        st.warning(
            f"The map needs two numeric feature columns, and this file has {found}. "
            "Overall performance above still applies."
        )
        explain_excluded(not_offered, expanded=True)
        return None

    left, right = st.columns(2)
    with left:
        x_col = pick_axis("X axis feature", options.usable, f"x::{dk}", avoid=st.session_state.get(f"y::{dk}"))
    with right:
        y_col = pick_axis("Y axis feature", options.usable, f"y::{dk}", avoid=x_col)
    explain_excluded(not_offered)

    if x_col == y_col:
        st.error("Choose two different features for the X and Y axes.")
        return None
    try:
        fmap = A.build_failure_map(raw, evaluation.rows, x_col, y_col, settings.n_bins)
    except A.DataError as exc:
        st.error(str(exc))
        return None

    # Clear the selected cell whenever the cells themselves may have changed.
    signature = repr((dk, roles.actual, roles.predicted, x_col, y_col, settings.n_bins))
    if st.session_state.get("selection_signature") != signature:
        st.session_state["selection_signature"] = signature
        st.session_state["sel_x"] = None
        st.session_state["sel_y"] = None
    chart_key = "map::" + hashlib.md5(signature.encode()).hexdigest()[:12]
    apply_map_click(f"{chart_key}::{st.session_state.get('map_clicks', 0)}")

    mapped_rate = float(fmap.rows["is_error"].mean())
    if fmap.n_omitted:
        reasons = "; ".join(f"{md(reason)}: {count:,}" for reason, count in fmap.omitted.items())
        st.caption(
            f"Mapping **{fmap.n_mapped:,} of {fmap.n_evaluated:,}** evaluated rows. "
            f"{plural(fmap.n_omitted, 'row')} left off this map ({reasons}); "
            "they still count in the overall accuracy."
        )
    else:
        st.caption(f"Mapping all **{fmap.n_mapped:,}** evaluated rows.")
    for axis_bins, column in ((fmap.x_bins, x_col), (fmap.y_bins, y_col)):
        if len(axis_bins) < settings.n_bins:
            st.caption(
                f"“{md(column)}” has only {len(axis_bins)} distinct whole-number values here, "
                f"so it uses {len(axis_bins)} ranges instead of {settings.n_bins}."
            )

    selected = (st.session_state.get("sel_x"), st.session_state.get("sel_y"))
    st.altair_chart(
        heatmap(fmap, settings.small_n, selected, theme_is_dark()),
        width="stretch",
        on_select="rerun",
        selection_mode="cell",
        key=f"{chart_key}::{st.session_state.get('map_clicks', 0)}",
    )
    st.caption(
        f"Colour = error rate on a fixed 0–100% scale; each cell shows its rate and "
        f"“errors of examples”. Grey = no examples (no rate, not 0%). “small” = fewer than "
        f"{settings.small_n} examples. Error rate across all mapped rows: {mapped_rate:.1%}. "
        "A high rate marks a group to investigate, not a cause."
    )
    with st.expander("Map as a table (highest error rate first)"):
        table = fmap.cells.assign(
            **{
                x_col: [fmap.x_bins.labels[i] for i in fmap.cells["x_bin"]],
                y_col: [fmap.y_bins.labels[i] for i in fmap.cells["y_bin"]],
                "small sample": A.small_cells(fmap.cells, settings.small_n),
            }
        ).sort_values(["error_rate", "total"], ascending=[False, False], na_position="last")
        st.dataframe(
            percent_table(table[[x_col, y_col, "total", "errors", "error_rate", "small sample"]], "error_rate"),
            hide_index=True,
            column_config={
                "total": st.column_config.NumberColumn("examples", format="%d"),
                "errors": st.column_config.NumberColumn(format="%d"),
                "error_rate": percent_column("error rate"),
            },
        )
    return fmap


def explain_excluded(not_offered: dict[str, str], expanded: bool = False) -> None:
    if not not_offered:
        return
    with st.expander("Why aren't other columns offered as axes?", expanded=expanded):
        st.markdown("\n".join(f"* **{md(column)}**: {md(reason)}" for column, reason in not_offered.items()))


# ---------------------------------------------------------------------------
# 4 · Inspect a cell


def show_rows(
    raw: pd.DataFrame,
    evaluation: A.Evaluation,
    index: pd.Index,
    roles: Roles,
    lead: tuple[str, ...],
    numeric: tuple[str, ...],
) -> pd.DataFrame:
    """The detail table: original columns, mapped columns first."""
    confidence = (roles.confidence,) if roles.confidence_ok else ()
    lead_columns = (*roles.ids, roles.actual, roles.predicted, *lead, *confidence)
    table = A.detail_table(raw, evaluation.rows["is_error"], index, lead_columns, (*numeric, *confidence))
    column_config = {
        table.columns[0]: st.column_config.NumberColumn(
            format="%d", help="Row number in the file (1 = first row after the header)."
        )
    }
    if confidence:
        column_config[roles.confidence] = st.column_config.ProgressColumn(
            min_value=0.0, max_value=1.0, format="%.2f", help="Probability the model gave to its predicted class."
        )
    st.dataframe(table, hide_index=True, column_config=column_config)
    return table


def inspect_section(
    raw: pd.DataFrame,
    evaluation: A.Evaluation,
    fmap: A.FailureMap,
    roles: Roles,
    numeric: tuple[str, ...],
    settings: Settings,
) -> A.CellStats | None:
    st.header("4 · Inspect a cell", divider="gray")
    left, middle, right = st.columns([5, 5, 2], vertical_alignment="bottom")
    with left:
        sel_x = st.selectbox(
            f"{md(fmap.x_col)} range",
            list(range(len(fmap.x_bins))),
            index=None,
            format_func=lambda i: fmap.x_bins.labels[i],
            placeholder="Choose a range",
            key="sel_x",
        )
    with middle:
        sel_y = st.selectbox(
            f"{md(fmap.y_col)} range",
            list(range(len(fmap.y_bins))),
            index=None,
            format_func=lambda i: fmap.y_bins.labels[i],
            placeholder="Choose a range",
            key="sel_y",
        )
    with right:
        errors_only = st.toggle(
            "Errors only",
            key="errors_only",
            help="Show only mistaken rows. The selected cell and its counts stay the same.",
        )

    if sel_x is None or sel_y is None:
        st.info(
            f"Select a {md(fmap.x_col)} range and a {md(fmap.y_col)} range to inspect "
            "examples, or click a cell on the map."
        )
        return None

    stats = fmap.cell(sel_x, sel_y)
    where = f"**{md(fmap.x_bins.describe(sel_x, fmap.x_col))}** and **{md(fmap.y_bins.describe(sel_y, fmap.y_col))}**"
    if stats.total == 0:
        st.info(f"No examples in this group: {where}.")
        return stats

    mapped_rate = float(fmap.rows["is_error"].mean())
    st.markdown(
        f"{where}: **{plural(stats.errors, 'error')} out of {plural(stats.total, 'example')}** "
        f"({stats.error_rate:.1%} error rate). Across all mapped rows the error rate is {mapped_rate:.1%}."
    )
    if stats.total < settings.small_n:
        st.warning(
            f"Small sample: only {plural(stats.total, 'example')}, so this rate could change "
            "a lot with more data."
        )

    cell_index = fmap.cell_index(sel_x, sel_y)
    if roles.confidence_ok:
        confidence = A.parse_numeric(raw.loc[cell_index, roles.confidence]).values
        means = A.confidence_by_result(confidence, evaluation.rows.loc[cell_index, "is_error"])
        parts = [
            f"{means[key]:.2f} on {word} predictions"
            for key, word in (("error", "wrong"), ("correct", "correct"))
            if means[key] is not None
        ]
        if parts:
            st.caption("Average confidence in this cell: " + ", ".join(parts) + ".")

    shown = fmap.cell_index(sel_x, sel_y, errors_only=errors_only)
    if errors_only and len(shown) == 0:
        st.info("This cell has no errors. Turn off “Errors only” to see its rows.")
    else:
        table = show_rows(raw, evaluation, shown, roles, lead=(fmap.x_col, fmap.y_col), numeric=numeric)
        suffix = " (errors only)" if errors_only else ""
        st.caption(f"Showing {len(shown):,} of the cell's {plural(stats.total, 'row')}{suffix}.")
        st.download_button(
            "Download these rows as CSV",
            table.to_csv(index=False).encode("utf-8"),
            file_name=f"failure_atlas_cell_{sel_x + 1}_{sel_y + 1}.csv",
            mime="text/csv",
            on_click="ignore",
        )
    with st.expander("Class mix in this cell"):
        st.caption("A cell's error rate can reflect which classes land in it.")
        st.dataframe(
            percent_table(A.class_breakdown(evaluation.rows.loc[cell_index]), "error rate"),
            hide_index=True,
            column_config={"error rate": percent_column()},
        )
    return stats


def consistency_footer(
    overview: A.Overview, fmap: A.FailureMap | None, selection: tuple, stats: A.CellStats | None
) -> None:
    checks = A.consistency_checks(overview, fmap)
    if fmap is not None and stats is not None:
        sel_x, sel_y = selection
        checks += [
            ("Selected cell: rows listed = examples on the map", len(fmap.cell_index(sel_x, sel_y)) == stats.total),
            (
                "Selected cell: error rows listed = errors on the map",
                len(fmap.cell_index(sel_x, sel_y, errors_only=True)) == stats.errors,
            ),
        ]
    failed = [name for name, ok in checks if not ok]
    if failed:
        st.error("Internal consistency check failed: " + "; ".join(failed) + ". Please report this.")
    with st.expander(f"Consistency checks: {'all passed' if not failed else f'{len(failed)} failed'}"):
        st.markdown("\n".join(f"* {'✅' if ok else '❌'} {name}" for name, ok in checks))


# ---------------------------------------------------------------------------


def main() -> None:
    st.set_page_config(page_title="Model Failure Atlas", page_icon="🗺️", layout="wide")
    with st.sidebar:
        dataset = choose_dataset()
        settings = map_settings()

    st.title("Model Failure Atlas")
    st.markdown(
        "The model has an overall score, but **which kinds of examples does it get wrong?** "
        "Load a CSV of existing predictions, map its label columns, and choose two numeric "
        "features. The map colours each group of examples by its error rate; open any "
        "cell to read the exact rows behind it. Nothing is trained or re-run here."
    )

    if dataset is None:
        st.info("Upload a CSV in the sidebar to begin, or switch back to the sample dataset.")
        with st.expander("What should the CSV look like?", expanded=True):
            st.markdown(CSV_HELP)
        return
    data, name, dk = dataset
    try:
        loaded = load(data)
    except A.DataError as exc:
        st.error(f"**{md(name)}** can't be used: {exc}")
        with st.expander("What should the CSV look like?", expanded=True):
            st.markdown(CSV_HELP)
        return
    raw = loaded.frame

    prepared = data_section(raw, loaded, name, dk)
    if prepared is None:
        return
    roles, evaluation = prepared
    overview = A.compute_overview(evaluation.rows)
    options = A.feature_options(raw, evaluation.rows.index, roles.reserved)
    overview_section(raw, evaluation, overview, roles, options.usable)

    fmap = failure_map_section(raw, evaluation, roles, options, settings, dk)
    stats = None
    if fmap is not None:
        stats = inspect_section(raw, evaluation, fmap, roles, options.usable, settings)
    consistency_footer(overview, fmap, (st.session_state.get("sel_x"), st.session_state.get("sel_y")), stats)


if __name__ == "__main__":
    main()
