"""Ai Error Map: where does a classifier get things wrong?

    streamlit run app.py

Analyze existing predictions or train a baseline on a labelled CSV.
Both workflows use analysis.py for metrics, maps, and row inspection.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, replace
from pathlib import Path

import altair as alt
import numpy as np
import pandas as pd
import streamlit as st

import analysis as A
import training as T
import diagnostics as D
import evaluation as E
import exports as X
import ui_training as U

SAMPLE_PATH = Path(__file__).parent / "sample_predictions.csv"
ANALYZE_MODE = "Analyze an existing prediction CSV"
TRAIN_MODE = "Train a model and evaluate it"

# Error rate is a magnitude, so it gets one hue from light to dark: steps
# 100-700 of a blue ramp, spread evenly over a fixed 0-100% domain. Dark
# themes flip the anchor so a higher rate is always the more prominent cell.
BLUE_RAMP = [
    "#cde2fb", "#b7d3f6", "#9ec5f4", "#86b6ef", "#6da7ec", "#5598e7", "#3987e5",
    "#2a78d6", "#256abf", "#1c5cab", "#184f95", "#104281", "#0d366b",
]
INK, WHITE, MUTED = "#0b0b0b", "#ffffff", "#898781"
EMPTY_FILL = "rgba(137, 135, 129, 0.16)"  # neutral wash that works on light and dark
DIAGONAL_FILL = "background-color: rgba(137, 135, 129, 0.18); font-weight: 600"
TEXT_FLIP = 0.58  # from ramp step 450 on, white text contrasts better than ink
MAX_MATRIX_CLASSES = 30

CSV_HELP = """
One row per evaluated example, with a header row. For example:

```text
image_id,actual,predicted,confidence,brightness,blur_px
img_00001,stop,no_entry,0.43,0.21,6.4
img_00002,yield,yield,0.91,0.77,1.2
```

* **Actual and predicted labels**: any column names; you choose them after uploading.
* **At least two numeric feature columns** to use as the map's axes.
* Optional: an ID column and a confidence column (the probability the model
  gave to the class it predicted, between 0 and 1).
"""


@dataclass(frozen=True)
class Settings:
    n_bins: int
    small_n: int
    method: str = "Equal width"
    palette: str = "Blue"
    show_counts: bool = True


@dataclass(frozen=True)
class Roles:
    actual: str
    predicted: str
    ids: tuple[str, ...]
    confidence: str | None  # the column picked as confidence, confirmed or not
    confidence_ok: bool  # confirmed as predicted-class probability and within 0-1
    task: str = "classification"
    probabilities: dict[str, str] | None = None
    extra_reserved: tuple[str, ...] = ()
    probability_note: str | None = None  # why a trained model has no class probabilities

    @property
    def reserved(self) -> dict[str, str]:
        """Columns that already have a role, so they can't be map axes."""
        reserved = {self.actual: "actual label", self.predicted: "predicted label"}
        reserved.update({column: "identifier" for column in self.ids})
        if self.confidence:
            reserved[self.confidence] = "confidence"
        reserved.update({column: "class probability" for column in (self.probabilities or {}).values()})
        reserved.update({column: "original prediction" for column in self.extra_reserved})
        return reserved


def md(text: object) -> str:
    """Escape text from the CSV so Markdown never reformats it."""
    return re.sub(r"([\\`*_{}\[\]()#+\-.!|$<>~])", r"\\\1", str(text))


def plural(n: int, word: str) -> str:
    return f"{n:,} {word if n == 1 else word + 's'}"


def percent_table(frame: pd.DataFrame, *columns: str) -> pd.DataFrame:
    """Rates (0-1) as percentages, for tables that show them to one decimal place."""
    return frame.assign(**{column: frame[column] * 100 for column in columns})


def percent_column(label: str | None = None):
    return st.column_config.NumberColumn(label, format="%.1f%%")


def theme_is_dark() -> bool:
    try:
        return st.context.theme.type == "dark"
    except Exception:  # no browser context, e.g. in tests
        return False


# The cache is shared by every visitor to a deployed app, so keep it small.
@st.cache_data(show_spinner=False, max_entries=4, ttl="1h")
def load(data: bytes) -> A.LoadedCSV:
    return A.load_csv(data)


@st.cache_data(show_spinner=False, max_entries=4, ttl="1h")
def dataset_fingerprint(data: bytes) -> str:
    """Computed once per upload and reused by caches, run signatures and metadata."""
    return T.fingerprint(load(data).frame)


# ---------------------------------------------------------------------------
# Sidebar


def choose_dataset() -> tuple[bytes, str, str] | None:
    """Returns (bytes, display name, dataset key); None while waiting for an upload."""
    st.subheader("Data")
    source = st.radio(
        "Data source",
        ["Sample dataset", "Upload a CSV"],
        key="source",
        label_visibility="collapsed",
    )
    if source == "Sample dataset":
        st.caption(
            "Synthetic results from a traffic-sign classifier on 1,200 images, "
            "generated by `scripts/make_sample_data.py`."
        )
        return SAMPLE_PATH.read_bytes(), SAMPLE_PATH.name, "sample"
    upload = st.file_uploader(
        "CSV of predictions",
        type=["csv"],
        key="upload",
        help="One row per evaluated example, with a header row.",
    )
    if upload is None:
        return None
    # A fresh upload gets a fresh key, even if it is the same file, so no
    # choices from the previous dataset carry over.
    return upload.getvalue(), upload.name, f"upload:{upload.file_id}"


def map_settings() -> Settings:
    st.subheader("Map settings")
    n_bins = st.select_slider(
        "Ranges per axis",
        options=list(range(2, 9)),
        value=A.DEFAULT_BINS,
        key="n_bins",
        help="Each feature is split into this many equal-width ranges. "
        "Changing it clears the selected cell.",
    )
    small_n = st.number_input(
        "Small-sample threshold",
        min_value=2,
        max_value=100_000,
        value=A.DEFAULT_SMALL_SAMPLE,
        step=1,
        key="small_n",
        help="Cells with fewer examples than this are marked as small samples, "
        "because their error rates are unreliable.",
    )
    method = st.selectbox("Binning method", ["Equal width", "Quantiles", "Custom boundaries"], key="bin_method")
    palette = st.selectbox("Colour palette", ["Blue", "Purple", "Teal"], key="palette")
    counts = st.checkbox("Show sample-count overlays", value=True, key="show_counts")
    return Settings(int(n_bins), int(small_n), method, palette, counts)


def training_dataset() -> tuple[bytes, str, str] | None:
    st.subheader("Training data")
    upload = st.file_uploader(
        "Labelled CSV", type=["csv"], key="train_upload",
        help="One row per example, with a target class and numeric feature columns.",
    )
    if upload is None:
        return None
    return upload.getvalue(), upload.name, f"train:{upload.file_id}"


def training_section(
    loaded: A.LoadedCSV, name: str, dk: str, task: str = "classification", fp: str | None = None,
) -> tuple[pd.DataFrame, Roles, A.Evaluation, str] | None:
    trained = U.training_controls(loaded, name, dk, task, fp)
    if trained is None:
        return None
    result, result_key = trained
    status = result.metadata.get("probability_status")
    roles = Roles(result.actual, result.predicted, result.ids, result.confidence, result.confidence is not None,
                  task=result.task, probabilities=result.probability_columns,
                  probability_note=None if result.probability_columns or status == "available" else status)
    evaluation = A.evaluate(result.frame, result.actual, result.predicted) if result.task == "classification" else E.regression_evaluation(result.frame, result.actual, result.predicted)
    return result.frame, roles, evaluation, result_key


# ---------------------------------------------------------------------------
# 1 · Data


def pick_column(label: str, options: list[str], guess: str | None, key: str, **kwargs) -> str | None:
    index = options.index(guess) if guess in options else None
    return st.selectbox(label, options, index=index, key=key, placeholder="Choose a column", **kwargs)


def data_section(raw: pd.DataFrame, loaded: A.LoadedCSV, name: str, dk: str, task: str = "classification", fp: str | None = None) -> tuple[Roles, A.Evaluation] | None:
    st.header("1 · Data", divider="gray")
    synthetic = " · synthetic demo data" if dk == "sample" else ""
    st.caption(f"**{md(name)}** · {len(raw):,} rows × {raw.shape[1]} columns{synthetic}")
    for note in loaded.notes:
        st.warning(md(note))
    with st.expander("Preview the first rows"):
        st.dataframe(raw.head(20))
    U.dataset_quality(raw, fp)

    columns = list(raw.columns)
    actual_guess, predicted_guess = A.suggest_label_columns(columns)
    left, right = st.columns(2)
    with left:
        actual_col = pick_column(
            "Actual label column" if task == "classification" else "Actual value column", columns, actual_guess, f"actual::{dk}",
            help="The observed class or numeric target for each example.",
        )
    with right:
        predicted_col = pick_column(
            "Predicted label column" if task == "classification" else "Predicted value column", columns, predicted_guess, f"predicted::{dk}",
            help="The model output for each example.",
        )
    if actual_col is None or predicted_col is None:
        st.info("Choose the actual and predicted label columns to continue.")
        return None
    if actual_col == predicted_col:
        st.error("The actual and predicted labels must come from two different columns.")
        return None

    label_warning = A.label_role_warning(raw, actual_col, predicted_col) if task == "classification" else None
    if label_warning:
        st.warning(label_warning)

    evaluation = A.evaluate(raw, actual_col, predicted_col) if task == "classification" else E.regression_evaluation(raw, actual_col, predicted_col)
    report_exclusions(evaluation)
    if evaluation.n_evaluated == 0:
        st.error(
            "No row has both an actual and a predicted label, so there is nothing to "
            "evaluate. Check the column choices above."
        )
        return None

    labels = pd.concat([evaluation.rows["actual"], evaluation.rows["predicted"]])
    variants = A.find_label_variants(labels) if task == "classification" else []
    if variants:
        shown = "; ".join(" / ".join(f"“{md(v)}”" for v in group) for group in variants[:6])
        more = f" (and {len(variants) - 6} more)" if len(variants) > 6 else ""
        st.warning(
            "Some labels differ only in capitalisation, spacing or number format: "
            f"{shown}{more}. They are treated as **different** classes, so a mismatch "
            "between them counts as an error. Fix the file if they mean the same thing."
        )

    with st.expander("Optional columns: identifiers and confidence"):
        roles = optional_roles(raw, evaluation, actual_col, predicted_col, dk, task)
    return roles, evaluation


def report_exclusions(evaluation: A.Evaluation) -> None:
    if evaluation.task == "regression":
        st.caption(f"{evaluation.n_uploaded:,} uploaded rows; {evaluation.n_evaluated:,} have finite numeric actual and predicted values. {evaluation.n_excluded:,} missing or non-numeric pairs excluded.")
        return
    if not evaluation.n_excluded:
        st.success(
            f"{evaluation.n_uploaded:,} rows uploaded. Every row has both labels, "
            f"so the analysis uses all {evaluation.n_evaluated:,} rows."
        )
        return
    reasons = [
        (evaluation.n_missing_actual, "no actual label"),
        (evaluation.n_missing_predicted, "no predicted label"),
        (evaluation.n_missing_both, "neither label"),
    ]
    detail = ", ".join(f"{n:,} with {reason}" for n, reason in reasons if n)
    st.warning(
        f"{evaluation.n_uploaded:,} rows uploaded. {plural(evaluation.n_excluded, 'row')} "
        f"excluded because the actual or predicted label was missing ({detail}). "
        f"Analysis uses {evaluation.n_evaluated:,} rows."
    )


def optional_roles(raw: pd.DataFrame, evaluation: A.Evaluation, actual: str, predicted: str, dk: str, task: str = "classification") -> Roles:
    others = [column for column in raw.columns if column not in (actual, predicted)]
    id_guess = A.suggest_id_columns(raw, exclude=(actual, predicted))
    ids = st.multiselect(
        "Identifier columns",
        others,
        default=[column for column in id_guess if column in others],
        key=f"ids::{dk}",
        help="IDs, codes and row numbers are never offered as map axes, even when "
        "they look numeric. Pre-filled with columns that look like identifiers.",
    )
    if task == "regression":
        return Roles(actual, predicted, tuple(ids), None, False, task=task)

    conf_options: list[str | None] = [None] + [column for column in others if column not in ids]
    conf_guess = A.suggest_confidence_column(conf_options[1:])
    confidence = st.selectbox(
        "Confidence column",
        conf_options,
        index=conf_options.index(conf_guess),
        format_func=lambda column: "None" if column is None else column,
        key=f"confidence::{dk}",
        help="Optional. Only used once you confirm what it means.",
    )
    confidence_ok = False
    if confidence is not None:
        confirmed = st.checkbox(
            f"“{md(confidence)}” is the probability the model gave to the class it predicted (0 to 1)",
            key=f"confidence_ok::{dk}::{confidence}",
            help="Not a positive-class probability and not a raw score. If unsure, leave "
            "this unticked: accuracy and the failure map don't need confidence.",
        )
        if confirmed:
            check = A.check_confidence(raw, evaluation.rows.index, confidence)
            if check.usable:
                confidence_ok = True
                st.caption(check.message)
            else:
                st.warning(check.message)
        else:
            st.caption("Confidence is shown in the tables only after you confirm its meaning.")
    return Roles(actual, predicted, tuple(ids), confidence, confidence_ok)


# ---------------------------------------------------------------------------
# 2 · Overall performance


def style_confusion(confusion: pd.DataFrame):
    def diagonal(frame: pd.DataFrame) -> pd.DataFrame:
        styles = pd.DataFrame("", index=frame.index, columns=frame.columns)
        for label in frame.index:
            if label in frame.columns:
                styles.loc[label, label] = DIAGONAL_FILL
        return styles

    return confusion.style.apply(diagonal, axis=None)


def overview_section(
    raw: pd.DataFrame, evaluation: A.Evaluation, overview: A.Overview, roles: Roles, numeric: tuple[str, ...],
    heldout: bool = False,
) -> None:
    st.header("2 · Held-out test performance" if heldout else "2 · Overall performance", divider="gray")
    tiles = st.columns(5)
    tiles[0].metric("Accuracy", f"{overview.accuracy:.1%}", border=True, help="Correct predictions ÷ evaluated rows.")
    tiles[1].metric(
        "Errors", f"{overview.n_errors:,}", border=True,
        help="Rows whose predicted label differs from the actual label.",
    )
    tiles[2].metric("Correct", f"{overview.n_correct:,}", border=True)
    tiles[3].metric(
        "Evaluated rows", f"{overview.n_evaluated:,}", border=True,
        help="Rows with both an actual and a predicted label: the denominator for accuracy.",
    )
    tiles[4].metric(
        "Excluded rows", f"{evaluation.n_excluded:,}", border=True,
        help="Rows missing a label. They are left out of every number on this page.",
    )
    st.caption(
        f"Accuracy = {overview.n_correct:,} correct ÷ {overview.n_evaluated:,} evaluated rows "
        f"(error rate {overview.error_rate:.1%}). Every row counts equally."
    )

    n_classes = len(overview.confusion)
    if n_classes > MAX_MATRIX_CLASSES and n_classes > 0.2 * overview.n_evaluated:
        st.warning(
            f"There are {n_classes:,} distinct labels. This app is built for classification; "
            "if these are continuous values, check the label columns."
        )

    left, right = st.columns([3, 2], gap="large")
    with left:
        st.subheader("Confusion matrix")
        if n_classes > MAX_MATRIX_CLASSES:
            st.info(f"{n_classes:,} classes are too many to show as a matrix. See the most common mistakes.")
        else:
            st.caption(
                "Rows are the actual class, columns the predicted class. "
                "The shaded diagonal counts correct predictions."
            )
            normalisation = st.radio("Confusion matrix values", ["Counts", "Actual class (%)", "Predicted class (%)"], horizontal=True, key="confusion_mode")
            matrix = E.normalise_confusion(overview.confusion, normalisation)
            if normalisation != "Counts":
                st.caption("Blank percentages indicate a class with no supporting rows for that denominator.")
            st.dataframe(style_confusion(matrix))
            st.download_button("Download displayed confusion matrix", matrix.to_csv().encode(), "confusion_matrix.csv", on_click="ignore")
        if overview.predicted_only:
            st.caption(
                "Predicted but never an actual label here: "
                + ", ".join(f"“{md(c)}”" for c in overview.predicted_only) + "."
            )
        if overview.never_predicted:
            st.caption(
                "Actual classes the model never predicted: "
                + ", ".join(f"“{md(c)}”" for c in overview.never_predicted) + "."
            )
    with right:
        st.subheader("Most common mistakes")
        mistakes = A.top_confusions(overview, limit=6)
        if mistakes.empty:
            st.success("No mistakes: every evaluated prediction is correct.")
        else:
            st.dataframe(
                percent_table(mistakes, "share of errors"),
                hide_index=True,
                column_config={
                    "errors": st.column_config.NumberColumn(format="%d"),
                    "share of errors": percent_column(),
                },
            )

    error_index = evaluation.rows.index[evaluation.rows["is_error"]]
    with st.expander(f"All {plural(len(error_index), 'error')}"):
        show_rows(raw, evaluation, error_index, roles, lead=(), numeric=numeric)

    metrics, per_class = E.classification_metrics(evaluation.rows)
    with st.expander("Precision, recall, F1 and class balance"):
        st.caption("Macro averages give every class equal weight; weighted averages use actual class support. Balanced accuracy is mean recall over actual classes. Undefined precision or recall is reported as 0.")
        st.dataframe(pd.DataFrame([{k: v for k, v in metrics.items() if k not in ("evaluated_rows", "correct", "errors")}]), hide_index=True)
        st.dataframe(per_class, hide_index=True)
        st.download_button("Download per-class metrics", per_class.to_csv(index=False).encode(), "per_class_metrics.csv", on_click="ignore")


def regression_overview(raw, evaluation, roles, numeric, heldout):
    st.header("2 · Held-out test performance" if heldout else "2 · Regression performance", divider="gray")
    metrics = E.regression_metrics(evaluation.rows)
    columns = st.columns(5)
    for column, label, key in zip(columns[:3], ("MAE", "RMSE", "R²"), ("mae", "rmse", "r2")):
        value = metrics[key]
        column.metric(label, "Undefined" if value is None else f"{value:.4g}", border=True)
    columns[3].metric("Evaluated rows", f"{evaluation.n_evaluated:,}", border=True)
    columns[4].metric("Excluded rows", f"{evaluation.n_excluded:,}", border=True)
    st.caption(f"MAE and RMSE use the target's units. Residual = predicted − actual. R² is undefined for a constant actual target or fewer than two rows. {metrics['above_tolerance']:,} rows have absolute error greater than {evaluation.tolerance:g}; changing this tolerance does not change MAE, RMSE or R².")
    with st.expander("Regression residuals"):
        chart = alt.Chart(evaluation.rows.head(5000)).mark_circle(opacity=.5).encode(x="actual:Q", y="residual:Q", tooltip=["actual", "predicted", "residual"])
        st.altair_chart(chart, width="stretch")
        st.caption("Scatter plot shows at most the first 5,000 evaluated rows; metrics use every evaluated row.")
    with st.expander("Rows above the absolute error tolerance"):
        show_rows(raw, evaluation, evaluation.rows.index[evaluation.rows["is_error"]], roles, (), numeric)
    return metrics


def probability_controls(raw, roles, evaluation, dk):
    """Require explicit positive-class semantics for uploaded probability columns."""
    probabilities = pd.DataFrame(index=raw.index)
    config = {}
    if roles.task != "classification":
        return raw, roles, evaluation, probabilities, config
    for label, column in (roles.probabilities or {}).items():
        probabilities[label] = A.parse_numeric(raw[column]).values
    classes = A.sort_labels(set(evaluation.rows["actual"]) | set(evaluation.rows["predicted"]))
    with st.expander("Class probabilities and binary thresholds"):
        st.caption("Predicted-class confidence and positive-class probability are different. Threshold changes are exploratory; choose deployment thresholds using training/validation data, then evaluate once on an untouched test set.")
        positive, negative, probability = None, None, None
        if len(classes) == 2:
            if len(probabilities.columns) == 2:
                positive = st.selectbox("Positive class", classes, index=1, key=f"positive::{dk}")
                negative = next(c for c in classes if c != positive)
                probability = roles.probabilities[positive]
            elif roles.probability_note:
                st.info(roles.probability_note)
            elif not len(probabilities.columns) and st.checkbox("Map a positive-class probability column", key=f"map_probability::{dk}"):
                positive = st.selectbox("Positive class", classes, index=1, key=f"positive::{dk}")
                negative = next(c for c in classes if c != positive)
                options = [c for c in raw if c not in (roles.actual, roles.predicted, *roles.ids)]
                probability = st.selectbox("Positive-class probability column", options, index=None, key=f"positive_column::{dk}")
                if probability and st.checkbox("This column is P(the selected positive class), between 0 and 1", key=f"positive_confirm::{dk}::{positive}::{probability}"):
                    values = A.parse_numeric(raw[probability]).values
                    probabilities[positive] = values
                    probabilities[negative] = 1 - values
                    roles = replace(roles, probabilities={positive: probability})
                else:
                    probability = None
            if probability:
                config = {"positive_class": positive, "negative_class": negative, "positive_probability_column": probability}
                if st.checkbox("Explore a decision threshold", key=f"threshold_on::{dk}"):
                    threshold = st.slider("Positive decision threshold", 0.0, 1.0, .5, .01, key=f"threshold::{dk}")
                    old_columns = set(raw)
                    raw, invalid = E.apply_threshold(raw, roles.predicted, probability, positive, negative, threshold)
                    backup = tuple(set(raw) - old_columns)
                    confidence_col = A._unique_name("threshold_confidence", raw.columns)
                    p = A.parse_numeric(raw[probability]).values
                    raw[confidence_col] = np.where(raw[roles.predicted] == positive, p, 1 - p)
                    roles = replace(roles, confidence=confidence_col, confidence_ok=True, extra_reserved=(*roles.extra_reserved, *backup))
                    evaluation = A.evaluate(raw, roles.actual, roles.predicted)
                    config.update(threshold=threshold, scope="Exploratory threshold on evaluation rows")
                    st.info(f"Active predictions now use P({md(positive)}) ≥ {threshold:.2f}. Metrics, the map, inspected rows and report downloads below use this threshold. The original fitted prediction is retained in an extra column.")
                    if invalid:
                        st.warning(f"{invalid:,} rows have missing or invalid probabilities; their threshold predictions are blank and excluded.")
                valid = probabilities[positive].between(0, 1) & A.clean_labels(raw[roles.actual]).notna()
                if valid.any():
                    truth = A.clean_labels(raw.loc[valid, roles.actual]) == positive
                    p = probabilities.loc[valid, positive]
                    points = []
                    for threshold in np.linspace(0, 1, 21):
                        pred = p >= threshold
                        tp = int((truth & pred).sum())
                        precision = tp / int(pred.sum()) if pred.sum() else 0
                        recall = tp / int(truth.sum()) if truth.sum() else 0
                        points.append({"threshold": threshold, "precision": precision, "recall": recall})
                    st.line_chart(pd.DataFrame(points), x="threshold", y=["precision", "recall"])
        elif len(classes) > 2:
            st.caption("Decision thresholds here apply to binary classification. Multiclass probabilities are used for ROC-AUC when available.")
            if roles.probability_note:
                st.info(roles.probability_note)
            elif probabilities.empty:
                probabilities, roles, config = class_probability_mapping(raw, roles, evaluation, classes, dk, probabilities)
        else:
            st.caption("At least two classes are needed for binary threshold exploration.")
        if probabilities.empty and not roles.probability_note:
            st.caption("ROC-AUC is unavailable until class probabilities are mapped: a CSV with only predicted labels cannot supply them.")
    return raw, roles, evaluation, probabilities, config


MAX_MAPPED_CLASSES = 20


def class_probability_mapping(raw, roles, evaluation, classes, dk, probabilities):
    """Uploaded multiclass CSVs: one confirmed probability column per class, validated in evaluation.py."""
    if not st.checkbox("Map class probability columns (multiclass ROC-AUC)", key=f"map_multiclass::{dk}"):
        return probabilities, roles, {}
    if len(classes) > MAX_MAPPED_CLASSES:
        st.info(f"There are {len(classes):,} classes; mapping is offered for up to {MAX_MAPPED_CLASSES}.")
        return probabilities, roles, {}
    options = [c for c in raw if c not in (roles.actual, roles.predicted, *roles.ids, roles.confidence)]
    guesses = E.suggest_probability_columns(options, classes)
    mapping = {}
    grid = st.columns(min(3, len(classes)))
    for i, label in enumerate(classes):
        with grid[i % len(grid)]:
            choices = [None, *options]
            mapping[label] = st.selectbox(
                f"P({md(label)})", choices, index=choices.index(guesses.get(label)),
                format_func=lambda c: "Choose a column" if c is None else c, key=f"class_probability::{dk}::{label}",
            )
    check = E.map_class_probabilities(raw, evaluation.rows, mapping, classes)
    for error in check.errors:
        st.error(error)
    for warning in check.warnings:
        st.warning(warning)
    if not check.usable:
        st.caption("ROC-AUC stays unavailable until every class has a valid probability column.")
        return probabilities, roles, {}
    stamp = hashlib.md5(repr(sorted(mapping.items())).encode()).hexdigest()[:10]
    if not st.checkbox("Each column is P(its class) between 0 and 1, from the same model as the predictions", key=f"multiclass_confirm::{dk}::{stamp}"):
        st.caption("Probabilities are used only after you confirm what the columns mean.")
        return probabilities, roles, {}
    mapped = check.probabilities.reindex(raw.index)
    return mapped, replace(roles, probabilities=dict(mapping)), {"class_probability_columns": dict(mapping)}


def confidence_section(raw, roles, evaluation, probabilities):
    metrics = {}
    with st.expander("Confidence and ROC-AUC"):
        average, strategy = "macro", "ovr"
        if not probabilities.empty and evaluation.rows["actual"].nunique() > 2:
            left, right = st.columns(2)
            average = left.radio("ROC-AUC average", E.AUC_AVERAGES, horizontal=True, key="auc_average")
            strategy = right.radio("Multiclass ROC-AUC", list(E.AUC_STRATEGIES), format_func=E.AUC_STRATEGIES.get, horizontal=True, key="auc_multi_class")
        auc, note = E.probability_auc(evaluation.rows, probabilities, average, strategy)
        if auc is not None:
            st.metric("ROC-AUC", f"{auc:.4f}")
            metrics.update(roc_auc=auc, roc_auc_average=average, roc_auc_multi_class=E.AUC_STRATEGIES[strategy])
            st.caption(note)
        elif roles.probability_note:
            st.info("ROC-AUC is unavailable because this model does not provide class probabilities. " + roles.probability_note)
        else:
            st.info(note)
        if not roles.confidence_ok:
            if roles.probability_note:
                st.info("Confidence analysis is unavailable because this model does not provide class probabilities.")
            else:
                st.caption("Choose and confirm a predicted-class confidence column under Optional columns to inspect confidence distributions.")
            return metrics
        values = A.parse_numeric(raw.loc[evaluation.rows.index, roles.confidence]).values
        valid = values.notna() & values.between(0, 1)
        frame = pd.DataFrame({"confidence": values[valid], "result": np.where(evaluation.rows.loc[valid, "is_error"], "Incorrect", "Correct")})
        if frame.empty:
            st.caption("There are no usable confidence values in this evaluation.")
            return metrics
        st.caption(f"{len(frame):,} of {evaluation.n_evaluated:,} evaluated rows have valid confidence. Compare confident mistakes with confident correct predictions.")
        st.dataframe(frame.groupby("result").agg(examples=("confidence", "size"), mean_confidence=("confidence", "mean")).reset_index(), hide_index=True)
        chart = alt.Chart(frame).mark_bar(opacity=.6).encode(x=alt.X("confidence:Q", bin=alt.Bin(step=.1, extent=[0, 1]), scale=alt.Scale(domain=[0, 1])), y="count():Q", color="result:N")
        st.altair_chart(chart, width="stretch")
        bins = E.confidence_bins(values, evaluation.rows["is_error"])
        st.dataframe(bins, hide_index=True)
        st.caption("Calibration by confidence bin: compare average confidence with observed accuracy. Empty bins have no rate; small bins are uncertain.")
    return metrics


# ---------------------------------------------------------------------------
# 3 · Failure map


def pick_axis(label: str, options: tuple[str, ...], key: str, avoid: str | None) -> str:
    preferred = next((column for column in options if column != avoid), options[0])
    return st.selectbox(label, options, index=options.index(preferred), key=key)


def heatmap(fmap: A.FailureMap, small_n: int, selected: tuple[int | None, int | None], dark: bool,
            metric: str = "error_rate", palette: str = "Blue", show_counts: bool = True) -> alt.LayerChart:
    cells = fmap.cells.copy()
    cells["x_range"] = [fmap.x_bins.labels[i] for i in cells["x_bin"]]
    cells["y_range"] = [fmap.y_bins.labels[i] for i in cells["y_bin"]]
    small = A.small_cells(cells, small_n).to_numpy()
    empty = (cells["total"] == 0).to_numpy()
    rate = cells[metric].to_numpy(dtype=float)
    metric_title = {"error_rate": "Error rate", "errors": "Errors", "mae": "Mean absolute error"}[metric]
    ceiling = 1.0 if metric == "error_rate" else max(float(cells[metric].max()), 1e-12)

    cells["rate_label"] = [(f"{r:.0%}" if metric == "error_rate" else f"{r:,.0f}" if metric == "errors" else f"{r:.3g}") if not e else "" for r, e in zip(rate, empty)]
    cells["count_label"] = [
        "" if e or not show_counts else (f"{total:,} examples" if metric == "mae" else f"{errors:,} of {total:,}") + (" · small" if s else "")
        for errors, total, e, s in zip(cells["errors"], cells["total"], empty, small)
    ]
    cells["tip_rate"] = [(f"{r:.1%}" if metric == "error_rate" else f"{r:.4g}") if not e else "no examples" for r, e in zip(rate, empty)]
    cells["tip_note"] = np.where(small, f"Small sample (fewer than {small_n})", np.where(empty, "Empty: no rate", ""))

    palettes = {"Blue": BLUE_RAMP, "Purple": ["#eee8f5", "#d2bce7", "#ab8bc9", "#8056ad", "#512882"], "Teal": ["#d9f0ed", "#ace0d8", "#68bcb1", "#28887e", "#07564d"]}
    ramp = palettes.get(palette, BLUE_RAMP)
    ramp = ramp[::-1] if dark else ramp
    normalized = rate / ceiling
    cells["dark_fill"] = (normalized <= 1 - TEXT_FLIP) if dark else (normalized >= TEXT_FLIP)
    # A condition, not a colour scale: a scale here would be merged with the
    # error-rate scale across layers, which Vega-Lite can't render.
    text_color = alt.when(alt.datum.dark_fill).then(alt.value(WHITE)).otherwise(alt.value(INK))

    n_x, n_y = len(fmap.x_bins), len(fmap.y_bins)
    big_font = 18 if max(n_x, n_y) <= 4 else 15 if max(n_x, n_y) <= 6 else 12
    small_font = 12 if max(n_x, n_y) <= 5 else 10
    cell_height = 92 if n_y <= 4 else 72 if n_y <= 6 else 56

    x = alt.X(
        "x_range:O",
        sort=list(fmap.x_bins.labels),
        title=fmap.x_col,
        scale=alt.Scale(paddingInner=0.015),
        axis=alt.Axis(labelAngle=0 if n_x <= 5 else -30, domain=False, ticks=False, labelPadding=8),
    )
    y = alt.Y(
        "y_range:O",
        sort=list(reversed(fmap.y_bins.labels)),
        title=fmap.y_col,
        scale=alt.Scale(paddingInner=0.03),
        axis=alt.Axis(domain=False, ticks=False, labelPadding=8),
    )
    base = alt.Chart(cells).encode(x=x, y=y)
    filled = base.transform_filter("datum.total > 0")

    layers = [
        filled.mark_rect(cornerRadius=3).encode(
            color=alt.Color(
                f"{metric}:Q",
                title=metric_title,
                scale=alt.Scale(domain=list(np.linspace(0, ceiling, len(ramp))), range=ramp, clamp=True),
                legend=alt.Legend(format=".0%" if metric == "error_rate" else ".3g", values=list(np.linspace(0, ceiling, 5)), gradientLength=cell_height * n_y * 0.6),
            )
        ),
        base.transform_filter("datum.total == 0").mark_rect(cornerRadius=3, color=EMPTY_FILL),
        filled.mark_text(fontSize=big_font, fontWeight=600, baseline="bottom", dy=-1).encode(
            text="rate_label:N", color=text_color
        ),
        filled.mark_text(fontSize=small_font, baseline="top", dy=3).encode(
            text="count_label:N", color=text_color
        ),
        base.transform_filter("datum.total == 0").mark_text(fontSize=small_font, color=MUTED).encode(
            text=alt.value("no examples")
        ),
    ]
    sel_x, sel_y = selected
    if sel_x is not None and sel_y is not None:
        layers.append(
            base.transform_filter(f"datum.x_bin == {int(sel_x)} && datum.y_bin == {int(sel_y)}").mark_rect(
                filled=False, stroke=WHITE if dark else INK, strokeWidth=3, cornerRadius=3
            )
        )
    # Invisible top layer: it takes hover and clicks for every cell, empty or not.
    pick = alt.selection_point(name="cell", fields=["x_bin", "y_bin"], on="click", clear=False)
    layers.append(
        base.mark_rect(opacity=0.001, cursor="pointer")
        .encode(
            tooltip=[
                alt.Tooltip("tip_rate:N", title=metric_title),
                alt.Tooltip("errors:Q", title="Errors", format=","),
                alt.Tooltip("total:Q", title="Examples", format=","),
                alt.Tooltip("x_range:N", title=fmap.x_col),
                alt.Tooltip("y_range:N", title=fmap.y_col),
                alt.Tooltip("tip_note:N", title="Note"),
            ]
        )
        .add_params(pick)
    )
    return (
        alt.layer(*layers)
        .properties(width="container", height=cell_height * n_y)
        .configure_view(stroke=None)
    )


def apply_map_click(chart_key: str) -> None:
    """Copy a click on the map into the two range selectors.

    After a click is applied the chart gets a new key, so its own selection
    state starts empty and the next click always registers as new.
    """
    state = st.session_state.get(chart_key)
    points = (state or {}).get("selection", {}).get("cell") or []
    if points and isinstance(points, list):
        st.session_state["sel_x"] = int(points[0]["x_bin"])
        st.session_state["sel_y"] = int(points[0]["y_bin"])
        st.session_state["map_clicks"] = st.session_state.get("map_clicks", 0) + 1


@st.cache_data(show_spinner=False, max_entries=12, ttl="1h")
def cached_failure_map(raw, rows, x, y, n_bins, method, x_edges, y_edges):
    return A.build_failure_map(raw, rows, x, y, n_bins, method, x_edges, y_edges)


def failure_map_section(
    raw: pd.DataFrame,
    evaluation: A.Evaluation,
    roles: Roles,
    options: A.FeatureOptions,
    settings: Settings,
    dk: str,
) -> A.FailureMap | None:
    st.header("3 · Failure map", divider="gray")
    map_evaluation = evaluation
    if roles.task == "classification":
        with st.expander("Filter map by class"):
            actual_filter = st.multiselect("Actual classes on map", A.sort_labels(evaluation.rows["actual"]), key=f"map_actual::{dk}")
            predicted_filter = st.multiselect("Predicted classes on map", A.sort_labels(evaluation.rows["predicted"]), key=f"map_predicted::{dk}")
            st.caption("An empty filter means all classes. Filters apply to the map and its inspected rows; the overall metrics above retain every evaluated row. Ranges are recalculated for the filtered rows.")
        map_evaluation = E.filter_evaluation(evaluation, tuple(actual_filter), tuple(predicted_filter))
    if map_evaluation.rows.empty:
        st.session_state["selection_signature"] = None
        st.session_state["sel_x"] = st.session_state["sel_y"] = None
        st.info("No evaluated rows match these map filters.")
        return None
    metric_options = {"Error rate": "error_rate", "Error count": "errors"} if roles.task == "classification" else {"Mean absolute error": "mae", "Above-tolerance rate": "error_rate", "Above-tolerance count": "errors"}
    metric_name = st.selectbox("Map colour represents", list(metric_options), key=f"map_metric::{dk}")
    metric = metric_options[metric_name]
    not_offered = {c: r for c, r in options.excluded.items() if c not in (roles.actual, roles.predicted)}

    if len(options.usable) < 2:
        found = f"only “{md(options.usable[0])}”" if options.usable else "none"
        st.warning(
            f"The map needs two numeric feature columns, and this file has {found}. "
            "Overall performance above still applies."
        )
        explain_excluded(not_offered, expanded=True)
        return None

    left, right = st.columns(2)
    with left:
        x_col = pick_axis("X axis feature", options.usable, f"x::{dk}", avoid=st.session_state.get(f"y::{dk}"))
    with right:
        y_col = pick_axis("Y axis feature", options.usable, f"y::{dk}", avoid=x_col)
    explain_excluded(not_offered)

    if x_col == y_col:
        st.error("Choose two different features for the X and Y axes.")
        return None
    x_edges = y_edges = None
    if settings.method == "Custom boundaries":
        def default_edges(column):
            try:
                return ", ".join(str(v) for v in A.make_bins(A.parse_numeric(raw.loc[map_evaluation.rows.index, column]).values, settings.n_bins).edges)
            except A.DataError:
                return ""
        x_text = st.text_input("X boundaries (comma separated)", default_edges(x_col), key=f"x_edges::{dk}::{x_col}")
        y_text = st.text_input("Y boundaries (comma separated)", default_edges(y_col), key=f"y_edges::{dk}::{y_col}")
        st.caption("Include both outer boundaries and every inner cut. They must increase strictly and cover all mapped values; values are never silently clipped into edge cells.")
        try:
            x_edges = tuple(float(v.strip()) for v in x_text.split(","))
            y_edges = tuple(float(v.strip()) for v in y_text.split(","))
        except ValueError:
            st.error("Enter numeric boundaries separated by commas.")
            return None
    try:
        fmap = cached_failure_map(raw, map_evaluation.rows, x_col, y_col, settings.n_bins, settings.method, x_edges, y_edges)
    except A.DataError as exc:
        st.error(str(exc))
        return None

    # Clear the selected cell whenever the cells themselves may have changed.
    row_signature = hashlib.sha256(pd.util.hash_pandas_object(map_evaluation.rows, index=True).values.tobytes()).hexdigest()
    signature = repr((dk, roles.actual, roles.predicted, x_col, y_col, settings.n_bins, settings.method, x_edges, y_edges, row_signature))
    if st.session_state.get("selection_signature") != signature:
        st.session_state["selection_signature"] = signature
        st.session_state["sel_x"] = None
        st.session_state["sel_y"] = None
        # Old chart events must not revive a selection when returning to a map.
        st.session_state["map_clicks"] = st.session_state.get("map_clicks", 0) + 1
    chart_key = "map::" + hashlib.md5(signature.encode()).hexdigest()[:12]
    apply_map_click(f"{chart_key}::{st.session_state.get('map_clicks', 0)}")

    mapped_rate = float(fmap.rows["is_error"].mean())
    if map_evaluation.n_evaluated != evaluation.n_evaluated:
        st.caption(f"Map filters retain {map_evaluation.n_evaluated:,} of {evaluation.n_evaluated:,} evaluated rows.")
    if fmap.n_omitted:
        reasons = "; ".join(f"{md(reason)}: {count:,}" for reason, count in fmap.omitted.items())
        st.caption(
            f"Mapping **{fmap.n_mapped:,} of {fmap.n_evaluated:,}** evaluated rows. "
            f"{plural(fmap.n_omitted, 'row')} left off this map ({reasons}); "
            "they still count in the overall metrics."
        )
    else:
        st.caption(f"Mapping all **{fmap.n_mapped:,}** evaluated rows.")
    for axis_bins, column in ((fmap.x_bins, x_col), (fmap.y_bins, y_col)):
        if len(axis_bins) < settings.n_bins:
            st.caption(
                f"“{md(column)}” uses {len(axis_bins)} ranges instead of {settings.n_bins}; "
                "limited distinct values or tied quantiles reduce the available ranges."
            )

    selected = (st.session_state.get("sel_x"), st.session_state.get("sel_y"))
    st.altair_chart(
        heatmap(fmap, settings.small_n, selected, theme_is_dark(), metric, settings.palette, settings.show_counts),
        width="stretch",
        on_select="rerun",
        selection_mode="cell",
        key=f"{chart_key}::{st.session_state.get('map_clicks', 0)}",
    )
    st.caption(
        f"Colour = {metric_name.lower()}. Rates use a fixed 0–100% scale; counts and MAE "
        f"use the current map's maximum. Grey = no examples (no rate, not 0%). “small” = fewer than "
        f"{settings.small_n} examples. {'Error' if roles.task == 'classification' else 'Above-tolerance'} rate across all mapped rows: {mapped_rate:.1%}. "
        "A high rate marks a group to investigate, not a cause."
    )
    with st.expander("Map as a table (highest error rate first)"):
        table = fmap.cells.assign(
            **{
                x_col: [fmap.x_bins.labels[i] for i in fmap.cells["x_bin"]],
                y_col: [fmap.y_bins.labels[i] for i in fmap.cells["y_bin"]],
                "small sample": A.small_cells(fmap.cells, settings.small_n),
            }
        ).sort_values([metric, "total"], ascending=[False, False], na_position="last")
        st.dataframe(
            percent_table(table[[x_col, y_col, "total", "errors", "error_rate", *(["mae", "mean_residual"] if roles.task == "regression" else []), "small sample"]], "error_rate"),
            hide_index=True,
            column_config={
                "total": st.column_config.NumberColumn("examples", format="%d"),
                "errors": st.column_config.NumberColumn(format="%d"),
                "error_rate": percent_column("error rate"),
            },
        )
        st.download_button("Download map table", X.map_table(fmap).to_csv(index=False).encode(), "map_cells.csv", on_click="ignore")
    return fmap


def explain_excluded(not_offered: dict[str, str], expanded: bool = False) -> None:
    if not not_offered:
        return
    with st.expander("Why aren't other columns offered as axes?", expanded=expanded):
        st.markdown("\n".join(f"* **{md(column)}**: {md(reason)}" for column, reason in not_offered.items()))


# ---------------------------------------------------------------------------
# 4 · Inspect a cell


def show_rows(
    raw: pd.DataFrame,
    evaluation: A.Evaluation,
    index: pd.Index,
    roles: Roles,
    lead: tuple[str, ...],
    numeric: tuple[str, ...],
) -> pd.DataFrame:
    """The detail table: original columns, mapped columns first."""
    confidence = (roles.confidence,) if roles.confidence_ok else ()
    lead_columns = (*roles.ids, roles.actual, roles.predicted, *lead, *confidence)
    table = A.detail_table(raw, evaluation.rows["is_error"], index, lead_columns, (*numeric, *confidence))
    if roles.task == "regression":
        table[table.columns[1]] = np.where(evaluation.rows.loc[index, "is_error"], "Above tolerance", "Within tolerance")
        for column in ("residual", "absolute_error"):
            table[A._unique_name(column, table.columns)] = evaluation.rows.loc[index, column].to_numpy()
    column_config = {
        table.columns[0]: st.column_config.NumberColumn(
            format="%d", help="Row number in the file (1 = first row after the header)."
        )
    }
    if confidence:
        column_config[roles.confidence] = st.column_config.ProgressColumn(
            min_value=0.0, max_value=1.0, format="%.2f", help="Probability the model gave to its predicted class."
        )
    st.dataframe(table, hide_index=True, column_config=column_config)
    return table


def inspect_section(
    raw: pd.DataFrame,
    evaluation: A.Evaluation,
    fmap: A.FailureMap,
    roles: Roles,
    numeric: tuple[str, ...],
    settings: Settings,
) -> A.CellStats | None:
    st.header("4 · Inspect a cell", divider="gray")
    left, middle, right = st.columns([5, 5, 2], vertical_alignment="bottom")
    with left:
        sel_x = st.selectbox(
            f"{md(fmap.x_col)} range",
            list(range(len(fmap.x_bins))),
            index=None,
            format_func=lambda i: fmap.x_bins.labels[i],
            placeholder="Choose a range",
            key="sel_x",
        )
    with middle:
        sel_y = st.selectbox(
            f"{md(fmap.y_col)} range",
            list(range(len(fmap.y_bins))),
            index=None,
            format_func=lambda i: fmap.y_bins.labels[i],
            placeholder="Choose a range",
            key="sel_y",
        )
    with right:
        errors_only = st.toggle(
            "Errors only" if roles.task == "classification" else "Above tolerance only",
            key="errors_only",
            help="Show only mistaken rows. The selected cell and its counts stay the same.",
        )

    if sel_x is None or sel_y is None:
        st.info(
            f"Select a {md(fmap.x_col)} range and a {md(fmap.y_col)} range to inspect "
            "examples, or click a cell on the map."
        )
        return None

    stats = fmap.cell(sel_x, sel_y)
    where = f"**{md(fmap.x_bins.describe(sel_x, fmap.x_col))}** and **{md(fmap.y_bins.describe(sel_y, fmap.y_col))}**"
    if stats.total == 0:
        st.info(f"No examples in this group: {where}.")
        return stats

    mapped_rate = float(fmap.rows["is_error"].mean())
    if roles.task == "classification":
        st.markdown(
            f"{where}: **{plural(stats.errors, 'error')} out of {plural(stats.total, 'example')}** "
            f"({stats.error_rate:.1%} error rate). Across all mapped rows the error rate is {mapped_rate:.1%}."
        )
    else:
        cell_rows = evaluation.rows.loc[fmap.cell_index(sel_x, sel_y)]
        st.markdown(f"{where}: **{stats.total:,} examples**, mean absolute error **{cell_rows['absolute_error'].mean():.4g}**. {stats.errors:,} rows ({stats.error_rate:.1%}) exceed the absolute error tolerance of {evaluation.tolerance:g}.")
    if stats.total < settings.small_n:
        st.warning(
            f"Small sample: only {plural(stats.total, 'example')}, so this rate could change "
            "a lot with more data."
        )

    cell_index = fmap.cell_index(sel_x, sel_y)
    if roles.confidence_ok:
        confidence = A.parse_numeric(raw.loc[cell_index, roles.confidence]).values
        means = A.confidence_by_result(confidence, evaluation.rows.loc[cell_index, "is_error"])
        parts = [
            f"{means[key]:.2f} on {word} predictions"
            for key, word in (("error", "wrong"), ("correct", "correct"))
            if means[key] is not None
        ]
        if parts:
            st.caption("Average confidence in this cell: " + ", ".join(parts) + ".")

    shown = fmap.cell_index(sel_x, sel_y, errors_only=errors_only)
    if errors_only and len(shown) == 0:
        st.info("This cell has no errors. Turn off “Errors only” to see its rows.")
    else:
        table = show_rows(raw, evaluation, shown, roles, lead=(fmap.x_col, fmap.y_col), numeric=numeric)
        suffix = " (errors only)" if errors_only else ""
        st.caption(f"Showing {len(shown):,} of the cell's {plural(stats.total, 'row')}{suffix}.")
        st.download_button(
            "Download these rows as CSV",
            table.to_csv(index=False).encode("utf-8"),
            file_name=f"failure_atlas_cell_{sel_x + 1}_{sel_y + 1}.csv",
            mime="text/csv",
            on_click="ignore",
        )
    if roles.task == "classification":
        with st.expander("Class mix in this cell"):
            st.caption("A cell's error rate can reflect which classes land in it.")
            st.dataframe(
                percent_table(A.class_breakdown(evaluation.rows.loc[cell_index]), "error rate"),
                hide_index=True,
                column_config={"error rate": percent_column()},
            )
    else:
        with st.expander("Residual summary in this cell"):
            st.dataframe(pd.DataFrame([E.regression_metrics(evaluation.rows.loc[cell_index])]), hide_index=True)
    return stats


def consistency_footer(
    overview: A.Overview | None, fmap: A.FailureMap | None, selection: tuple, stats: A.CellStats | None,
    evaluation: A.Evaluation | None = None,
) -> None:
    checks = A.consistency_checks(overview, fmap) if overview is not None else [
        ("Every regression row has finite residuals", bool(np.isfinite(evaluation.rows["residual"]).all())),
    ]
    if overview is None and fmap is not None:
        checks += [
            ("Cell counts add up to mapped rows", int(fmap.cells["total"].sum()) == fmap.n_mapped),
            ("Cell above-tolerance counts match rows", int(fmap.cells["errors"].sum()) == int(fmap.rows["is_error"].sum())),
            ("Mapped + omitted = map scope", fmap.n_mapped + fmap.n_omitted == fmap.n_evaluated),
        ]
    if fmap is not None and stats is not None:
        sel_x, sel_y = selection
        checks += [
            ("Selected cell: rows listed = examples on the map", len(fmap.cell_index(sel_x, sel_y)) == stats.total),
            (
                "Selected cell: error rows listed = errors on the map",
                len(fmap.cell_index(sel_x, sel_y, errors_only=True)) == stats.errors,
            ),
        ]
    failed = [name for name, ok in checks if not ok]
    if failed:
        st.error("Internal consistency check failed: " + "; ".join(failed) + ". Please report this.")
    with st.expander(f"Consistency checks: {'all passed' if not failed else f'{len(failed)} failed'}"):
        st.markdown("\n".join(f"* {'✅' if ok else '❌'} {name}" for name, ok in checks))


def reports_section(raw, evaluation, metadata, fmap, selected, result=None):
    with st.expander("Download evaluation report and audit files"):
        st.caption("The report includes active metrics, confusion matrices or residuals, map counts and row assignments, full selected-cell rows, predictions and provenance. Training metadata and cross-validation results are included when available. Files reflect the current threshold, tolerance and map filters.")
        meta = dict(metadata)
        meta["selected_cell_display_errors_only"] = bool(st.session_state.get("errors_only", False))
        stamp = hashlib.sha256(X.json_bytes([meta, selected, fmap.x_bins.edges if fmap else None, fmap.y_bins.edges if fmap else None])).hexdigest()
        if st.button("Prepare evaluation report", key="prepare_report"):
            with st.spinner("Preparing CSV, JSON and HTML report files…"):
                files = X.evaluation_files(raw, evaluation, meta, fmap, selected)
                if result is not None and not result.cv_results.empty:
                    files["cross_validation_results.csv"] = result.cv_results.to_csv(index=False).encode()
                st.session_state["prepared_report"] = (stamp, files, X.bundle(files))
        saved = st.session_state.get("prepared_report")
        if saved and saved[0] == stamp:
            _, files, archive = saved
            st.download_button("Download complete evaluation bundle", archive, "atlas_evaluation.zip", mime="application/zip", on_click="ignore")
            st.download_button("Download HTML evaluation report", files["evaluation_report.html"], "evaluation_report.html", mime="text/html", on_click="ignore")
            st.download_button("Download audit metadata", files["audit_metadata.json"], "audit_metadata.json", mime="application/json", on_click="ignore")


# ---------------------------------------------------------------------------


def main() -> None:
    st.set_page_config(page_title="AI Error Heatmap", page_icon="🗺️", layout="wide")
    st.title("Model Failure Atlas")
    mode = st.radio("Workflow", [ANALYZE_MODE, TRAIN_MODE], horizontal=True, key="workflow")
    task = st.radio("Prediction task", ["Classification", "Regression"], horizontal=True, key="prediction_task").lower()
    st.caption(
        "Analyze an existing prediction CSV requires both actual and predicted label columns. "
        "Train a model and evaluate it requires a target and feature columns. Classification "
        "predicts a class; regression predicts a numeric value. Training mode generates held-out predictions."
    )
    if st.session_state.get("active_mode") != (mode, task):
        st.session_state["active_mode"] = (mode, task)
        st.session_state.pop("training_result", None)
        st.session_state.pop("selection_signature", None)
        st.session_state["sel_x"] = None
        st.session_state["sel_y"] = None
        st.session_state["errors_only"] = False
    with st.sidebar:
        dataset = choose_dataset() if mode == ANALYZE_MODE else training_dataset()
        settings = map_settings()

    st.markdown(
        "The model has an overall score, but **which kinds of examples does it get wrong?** "
        "Choose two numeric features to map groups by error rate or error magnitude; "
        "open any cell to read the exact rows behind it."
    )

    if dataset is None:
        st.info("Upload a CSV in the sidebar to begin.")
        if mode == ANALYZE_MODE:
            with st.expander("What should the CSV look like?", expanded=True):
                st.markdown(CSV_HELP)
        else:
            st.caption("Use a header row, a target column and at least one numeric feature. For classification, try iris.csv with species. Use Regression for measurements such as sulphates.")
        return
    data, name, dk = dataset
    try:
        loaded = load(data)
    except A.DataError as exc:
        st.error(f"**{md(name)}** can't be used: {exc}")
        return
    raw = loaded.frame
    fp = dataset_fingerprint(data)

    if mode == TRAIN_MODE:
        trained = training_section(loaded, name, dk, task, fp)
        if trained is None:
            return
        raw, roles, evaluation, dk = trained
    else:
        try:
            prepared = data_section(raw, loaded, name, dk, task, fp)
        except A.DataError as exc:
            st.error(str(exc))
            return
        if prepared is None:
            return
        roles, evaluation = prepared
    result = st.session_state.get("training_result") if mode == TRAIN_MODE else None
    task = roles.task
    metadata = dict(result.metadata) if result is not None else {
        "performance_scope": "Uploaded prediction performance; split provenance unverified",
        "source_file": name, "dataset_sha256": hashlib.sha256(data).hexdigest(),
    }
    metadata.update(actual_column=roles.actual, predicted_column=roles.predicted, id_columns=roles.ids)
    if task == "regression":
        tolerance = st.number_input("Absolute error tolerance", min_value=0.0, value=0.0, step=.1, key=f"tolerance::{dk}", help="Used only to count rows above tolerance and filter inspection. MAE/RMSE/R² still use every numeric pair.")
        try:
            evaluation = E.regression_evaluation(raw, roles.actual, roles.predicted, tolerance)
        except A.DataError as exc:
            st.error(str(exc))
            return
        probabilities = pd.DataFrame()
        metadata["error_tolerance"] = tolerance
    else:
        raw, roles, evaluation, probabilities, probability_config = probability_controls(raw, roles, evaluation, dk)
        metadata["probability_settings"] = probability_config
    if not evaluation.n_evaluated:
        st.warning("No usable actual/predicted pairs remain for these settings.")
        return
    options = A.feature_options(raw, evaluation.rows.index, roles.reserved)
    if task == "classification":
        overview = A.compute_overview(evaluation.rows)
        overview_section(raw, evaluation, overview, roles, options.usable, heldout=mode == TRAIN_MODE)
        metadata["probability_metrics"] = confidence_section(raw, roles, evaluation, probabilities)
    else:
        overview = None
        regression_overview(raw, evaluation, roles, options.usable, heldout=mode == TRAIN_MODE)

    fmap = failure_map_section(raw, evaluation, roles, options, settings, dk)
    stats = None
    if fmap is not None:
        stats = inspect_section(raw, evaluation, fmap, roles, options.usable, settings)
    selected = (st.session_state.get("sel_x"), st.session_state.get("sel_y"))
    if result is not None:
        U.model_explanations(result, dk)
    metadata["map_settings"] = {
        "binning": settings.method, "requested_bins": settings.n_bins, "small_sample_threshold": settings.small_n,
        "palette": settings.palette, "display_metric": st.session_state.get(f"map_metric::{dk}"),
        "actual_class_filter": st.session_state.get(f"map_actual::{dk}", []),
        "predicted_class_filter": st.session_state.get(f"map_predicted::{dk}", []),
    }
    reports_section(raw, evaluation, metadata, fmap, selected, result)
    consistency_footer(overview, fmap, selected, stats, evaluation)


if __name__ == "__main__":
    main()
