"""Freeze the dependency graph of a clean, verified Python 3.12 environment."""

from importlib.metadata import requires, version
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]
RUNTIME = ["streamlit", "pandas", "numpy", "altair", "scikit-learn", "scipy"]


def closure(roots):
    found, queue = set(), list(roots)
    environments = [{**default_environment(), "platform_system": system, "sys_platform": sys, "extra": ""}
                    for system, sys in (("Linux", "linux"), ("Darwin", "darwin"))]
    while queue:
        name = canonicalize_name(queue.pop())
        if name in found:
            continue
        version(name)  # fail if an applicable platform dependency has not been installed
        found.add(name)
        for item in requires(name) or []:
            dep = Requirement(item)
            if dep.marker is None or any(dep.marker.evaluate(env) for env in environments):
                queue.append(dep.name)
    return found


def main():
    runtime = closure(RUNTIME)
    dev = closure([*RUNTIME, "pytest", "ruff", "pre-commit"])
    for filename, packages, prefix in (("requirements-lock.txt", runtime, ""),
                                       ("requirements-dev-lock.txt", dev-runtime, "-r requirements-lock.txt\n")):
        lines = ["# Generated by scripts/lock_dependencies.py from a verified Python 3.12 environment.",
                 "# Exact package versions for Linux/macOS; update intentionally and rerun the suite."]
        if prefix:
            lines.append(prefix.strip())
        for name in sorted(packages):
            marker = '; platform_system != "Darwin"' if name == "watchdog" else ""
            lines.append(f"{name}=={version(name)}{marker}")
        (ROOT / filename).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
